module SkelChi where

-- Haskell module generated by the BNF converter

import AbsChi
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transConstructor :: Constructor -> Result
transConstructor x = case x of
  Constructor string -> failure x
transVariable :: Variable -> Result
transVariable x = case x of
  Variable string -> failure x
transExp :: Exp -> Result
transExp x = case x of
  Apply exp1 exp2 -> failure x
  Lambda variable exp -> failure x
  Case exp brs -> failure x
  Rec variable exp -> failure x
  Var variable -> failure x
  Const constructor exps -> failure x
transBr :: Br -> Result
transBr x = case x of
  Branch constructor variables exp -> failure x

